# File: .github/workflows/build.yml
name: PonGo-Backend-Build-And-Push

on:
  push:
    branches: [ "main" ]
    paths: # Only trigger on changes to Go files, mod/sum, Dockerfile, or this workflow
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.github/workflows/build.yml'
    tags: # Trigger on version tags like v1.0.0, v0.1 etc.
      - 'v*'
  pull_request:
    branches: [ "main" ]
    paths: # Only trigger on changes to Go files, mod/sum, Dockerfile, or this workflow
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.github/workflows/build.yml'

jobs:
  build-and-push:
    name: Build Go Backend & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: 'go.sum'

      - name: Verify dependencies
        run: go mod verify

      - name: Remove vendor directory if exists # Ensure module cache is used
        run: rm -rf vendor

      - name: Build Go Application (for verification)
        run: go build -v ./... # Build all packages verbosely

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        # Login only if pushing a v* tag OR pushing to main branch
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/pongo # Your Docker Hub image name
          tags: |
            # tag latest when pushing to main OR pushing a v* tag
            # --- CORRECTED LINE: Removed {{ }} ---
            type=raw,value=latest,enable=is_default_branch || startsWith(github.ref, 'refs/tags/v')

            # tag with the version number when pushing a v* tag (e.g. v1.2.3 -> 1.2.3)
            type=ref,event=tag,pattern=v(.*)

      - name: Build and push Docker image
        # Run only if pushing a v* tag OR pushing to main branch
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} # Add labels generated by metadata action
          cache-from: type=gha
          cache-to: type=gha,mode=max