# File: .github/workflows/build.yml
name: PonGo-Backend-Build-And-Push

on:
  push:
    branches: [ "main" ]
    paths: # Only trigger on changes to Go files, mod/sum, Dockerfile, or this workflow
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ "main" ]
    paths: # Only trigger on changes to Go files, mod/sum, Dockerfile, or this workflow
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.github/workflows/build.yml'

jobs:
  build-and-push:
    name: Build Go Backend & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: 'go.sum'

      - name: Verify dependencies
        run: go mod verify

      - name: Remove vendor directory if exists # Ensure module cache is used
        run: rm -rf vendor

      - name: Build Go Application (for verification)
        run: go build -v ./... # Build all packages verbosely

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only login on push to main
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only build/push on push to main
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pongo:latest # Replace with your Docker Hub username
          # Optional: Add more tags like git sha: ${{ github.sha }}
          # tags: |
          #   ${{ secrets.DOCKERHUB_USERNAME }}/pongo:latest
          #   ${{ secrets.DOCKERHUB_USERNAME }}/pongo:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max